name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # change to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build Docker image
      run: docker build -t madhavikadam/demo1:30 .
      
    - name: Push Docker image to Docker Hub
      run: docker push madhavikadam/demo1:30
      
 
